### ISSUE TITLE
problems with plot limits using data with ultra small axis range

### ISSUE THREAD

**Issue by prjemian** [nexpy/nexpy#53] opened 2015-04-01 17:28 UTC
Running NeXpy 0.5.4 on Linux to plot data from a USAXS instrument (reaches "ultra small" Q values).  The width of the central optics peak in the raw data can be < 0.0005 degrees.  Problems come when trying to select plot limits to bracket parts of the central peak.

[1] sliders are unpredictable

On the plot, choosing the "x" tab, min and max limits are shown along with slider bars.  Using the slider bars, the scaling of the plot is very unpredictable.  Maybe takes some experience but the intuition needed is not obvious. 

[2] axis min/max entry boxes default to (+/-) 0.05 for smallest values

Typing values into the entry boxes for min and max is frustrating. Something is limiting the smallest value typed to (+/-) 0.01.  Anything smaller and the value reverts to a default (+/-) 0.05. 

[3] underflow observed in dialog: Change Plot Limits 

Menu bar->
  Window ->
  Change Plot Limits
  xMin = -0.0005
  xMax = 0.0005

results in this error to the console and no change in limits:
jemian@gov .../USAXS/livedata $ /local/Apps/anaconda/lib/python2.7/site-packages/matplotlib/axes/_base.py:2562: UserWarning: Attempting to set identical left==right results
in singular transformations; automatically expanding.
left=-0.0, right=-0.0
  'left=%s, right=%s') % (left, right))

Looks like an underflow caused when the numerical value was written to a string for the text entry widget. 

[4] single-axis mouse zoom not supported

Since I only want to zoom on one axis, using the mouse to drag a rectangle causes some data on the other axis to move off screen. It's not possible to first mouse zoom and then correct the other axis with the dialog box, the dialog shows numbers of the fully-expanded limits.  Expected the dialog to pick up the values being used on the displayed plot.

**Comment by rayosborn** [comment] 2015-04-01 18:22
I'm not sure if this fixes your issues, but if you click on "Change Plot Limits" in the Window menu, you can adjust the minimum and maximum values of the sliders. This is the only way to set the limits outside the default plot limits, but it can also be used to decrease the range and so increase the sensitivity of the sliders themselves. Right-clicking will reset them to the defaults. Let me know if that's a help.

**Comment by prjemian** [comment] 2015-04-01 21:39
Helps only a little.  There's something very wrong with the sliders.  

With the peak centered in view, limits set in the dialog to -0.001 and 0.001 moving one slider so the peak is zoomed some but stays fully in view, then moving the other slider by any amount at all causes the peak to move to the far edge of the plot.

**Comment by prjemian** [comment] 2015-04-01 21:40
Basically, that last is a report of [3] and [1] together.

**Comment by rayosborn** [comment] 2015-04-01 22:59
I suspect that the problem isn't with the sliders - it's with the double spin boxes, which default to too small a precision when the range is small. I don't customize those - they use the default PySide settings, but it might be necessary to tune the number of decimal places manually, something I would have preferred to avoid.

**Comment by prjemian** [comment] 2015-04-02 00:25
You commented on problem [3].  The sliders have their own separate problem [1].

**Comment by rayosborn** [comment] 2015-04-02 01:31
There is a feedback between the two. If, by default, QDoubleSpinBoxes have too low a precision, then that affects how the sliders respond. Without seeing your file, I'm not sure I exactly understand the issue, but I will upload an attempt to fix the precision problem to the nexusformat branch soon. We'll have to see if that helps.

**Comment by rayosborn** [comment] 2015-04-02 03:02
I have uploaded to the nexusformat branch a new version of plotview.py, which increases the precision of the double-spin-boxes when the total range is very small. If this doesn't help the slider issue, then I'll have another look.

**Comment by rayosborn** [comment] 2015-04-09 15:45
Have you been able to test if this change to plotview.py fixes the problem?

**Comment by prjemian** [comment] 2015-04-09 19:04
Starting nexpygui on the nexusformat branch fails.
First, needed pyro4, installed ok with pip.
Then needed globus.  Could not install with pip.

Why is globus needed?

mintadmin@mintadmin-vbox ~/.../nexpy/src/nexpy $ ./nexpygui.py test_calc.h5 &
[1] 2406
mintadmin@mintadmin-vbox ~/.../nexpy/src/nexpy $ Traceback (most recent call last):
  File "./nexpygui.py", line 28, in <module>
    main()
  File "./nexpygui.py", line 23, in main
    from nexpy.gui.consoleapp import main
  File "/home/mintadmin/Documents/eclipse/nexpy/src/nexpy/gui/consoleapp.py", line 48, in <module>
    from mainwindow import MainWindow
  File "/home/mintadmin/Documents/eclipse/nexpy/src/nexpy/gui/mainwindow.py", line 47, in <module>
    from remotedialogs import RemoteDialog
  File "/home/mintadmin/Documents/eclipse/nexpy/src/nexpy/gui/remotedialogs.py", line 20, in <module>
    from nexusformat.pyro.globus import GlobusCatalog
ImportError: No module named globus
^C
[1]+  Exit 1                  ./nexpygui.py test_calc.h5
mintadmin@mintadmin-vbox ~/.../nexpy/src/nexpy $ pip install globus
You are using pip version 6.0.8, however version 6.1.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Collecting globus
  Could not find any downloads that satisfy the requirement globus
  No distributions at all found for globus

**Comment by rayosborn** [comment] 2015-04-09 19:24
I've uploaded a new version, which should remove this dependency. I already had an import check on the Globus Catalog software, but it needed changing to account for a refactoring of the code. The globus module itself will be part of the nexusformat package at the next release, but still without making Pyro4 a dependency. Please let me know if the import check works. I can't test it easily myself.

**Comment by prjemian** [comment] 2015-04-09 19:36
the import check works

Tried to set plot limits in the double spin boxes but those were pegged at 0.05 and no smaller.  Needs experience with it before it can be declared intuitive.  Is that a MatPlotLib idiosyncracy?

The sliders are more predictable iff the xmin & xmax are changed in the Change Plot Limits dialog box.  Changed xmin=-0.005 and xmax=0.005 and was able to use the sliders to bracket the peak.  Also, the plot did not jump around to the opposite limit when a slider was moved.

**Comment by rayosborn** [comment] 2015-04-09 19:47
I don't think it's a Matplotlib issue; I think it's to do with the number of decimal places in the double spin boxes, restricting the precision with which you can set the limits. I'll have to think of a better long-term solution, but the Change Plot Limits dialog is designed for this kind of situation.

**Comment by prjemian** [comment] 2015-04-09 19:48
Then this problem reported is resolved.

**Comment by rayosborn** [comment] 2015-04-10 23:21
A follow-up comment. It has taken me a while to realize this, but I can now change the behavior of the minimum and maximum boxes so that, for those tabs with sliders, editing the text will change the limit, i.e., it will automatically change the sensitivity of the slider. The original limits can be reset by right-clicking on the graph or clicking on the Home button in the Options Tab. This is much more convenient than opening the Change Plot Limits dialog.

**Closed** 2015-06-08 21:49 UTC
