### ISSUE TITLE
fitting issue

### ISSUE THREAD

**Issue by jpcastell** [nexpy/nexpy#73] opened 2016-01-19 14:04 UTC
When doing a test fit of the following nxdata object
===================
x=np.linspace(-10,10,101)
y=3.0*x+5.0
e=np.sqrt(np.abs(y))
A=NXdata(y,x,errors=e)
=========================

the initial guess is correct for a linear fit.  3 and 5.  If you change the initial guess to anything the fit fails to find 3 and 5 again.  I am not seeing any errors pop up.

**Comment by rayosborn** [comment] 2016-01-19 15:24
I'm not having any problems. Can you give examples of start parameters that fail? Also, if you're testing this, it might be better to add some randomness to the y values. For a simple line, non-linear least-squares is overkill - we should probably switch to some linear regression method.

**Comment by jpcastell** [comment] 2016-01-19 15:33
It seems that after the initial guess phase if any parameter is changed it no longer attempts to fit.  
for example if you change the constant to 3 and ask it to fit it remains at 3 and calculates a new larger chi --- still reporting fit successful.

**Comment by jpcastell** [comment] 2016-01-19 15:36
I have recently updated my packages.  I see lmfit is now at version 0.9.2.  Are you still on 0.8.3?

**Comment by rayosborn** [comment] 2016-01-19 15:40
I'm still on 0.8.3. Have you tried Gaussian fits to real data? Is it completely broken or just with this function?

**Comment by jpcastell** [comment] 2016-01-19 15:40
Reading the change log for lmfit it seems to be the likely cause.
""""
This upgrade means that a script that does:

my_pars = Parameters()
my_pars.add('amp',    value=300.0, min=0)
my_pars.add('center', value=  5.0, min=0, max=10)
my_pars.add('decay',  value=  1.0, vary=False)

result = minimize(objfunc, my_pars)
will still work, but that my_pars will NOT be changed by the fit. Instead, my_pars is copied to an internal set of parameters that is changed in the fit, and this copy is then put in result.params. To look at fit results, use result.params, not my_pars.
"""

**Comment by rayosborn** [comment] 2016-01-19 15:46
OK - that's something I'll have to check for in the code. Thanks for the heads-up. By the way, I have a version of NeXpy that plots skewed axes. I hope to release it later this week. It's in the 'skewed-axes' branch of my repository at https://github.com/rayosborn/nexpy.

**Comment by rayosborn** [comment] 2016-01-24 02:39
@jpcastell, I have issued PR #75, which you could test if you pull my branch into your repository. My version of lmfit still seems to be broken, but I wanted to see if you had other experiences.

**Comment by rayosborn** [comment] 2016-01-25 01:39
I think I've fixed it. See PR #75. I'll do a couple more tests and then merge it.

**Comment by rayosborn** [comment] 2016-01-25 04:14
@jpcastell, I have merged PR #75, so this issue should be fixed in the master branch. If you can confirm it's fixed, I'll close the issue.

**Comment by jpcastell** [comment] 2016-01-26 10:28
I just tested with lmfit version 0.9.2 and it seems to be working now.

**Comment by rayosborn** [comment] 2016-01-26 15:22
Thanks. I'll close this then. There is a new release on PyPI, v0.7.0, although I'm not sure the conda build is working yet.

**Closed by rayosborn** 2016-01-26 15:22 UTC
