### ISSUE TITLE
NeXPy Recursion Error

### ISSUE THREAD

**Issue by spc93** [nexpy/nexpy#366] opened 2022-06-23 15:54 UTC
Hi, I seem to get an error (below) using NeXPy 0.14.5 when opening the attached NeXus file and selecting the /entry1/classic_scan group. We have looked at the links and can't see any problems (although we may have missed something). Would it be possible to check this?
Thanks!
Steve

RecursionError: maximum recursion depth exceeded while calling a Python object

---------------------------------------------------------------------------
RecursionError                            Traceback (most recent call last)
/dls_sw/apps/python/miniforge/4.10.0-0/envs/python3.10/lib/python3.10/site-packages/nexpy/gui/treeview.py in expand_node(self, index)
    432             group = item.node
    433             for name in [n for n in group if isinstance(group[n], NXgroup)]:
--> 434                 _entries = group[name].entries
    435 
    436     def addMenu(self, action):

/dls_sw/apps/python/miniforge/4.10.0-0/envs/python3.10/lib/python3.10/site-packages/nexusformat/nexus/tree.py in entries(self)
   5450         if _entries != self._entries:
   5451             self._entries = _entries
[938290.zip](https://github.com/nexpy/nexpy/files/8968829/938290.zip)

-> 5452             self.set_changed()
   5453         return _entries
   5454 

/dls_sw/apps/python/miniforge/4.10.0-0/envs/python3.10/lib/python3.10/site-packages/nexusformat/nexus/tree.py in set_changed(self)
   2276         self._changed = True
   2277         if self.nxgroup:
-> 2278             self.nxgroup.set_changed()
   2279 
   2280     def set_unchanged(self, recursive=False):

/dls_sw/apps/python/miniforge/4.10.0-0/envs/python3.10/lib/python3.10/site-packages/nexusformat/nexus/tree.py in set_changed(self)
   2276         self._changed = True
   2277         if self.nxgroup:
-> 2278             self.nxgroup.set_changed()
   2279 
   2280     def set_unchanged(self, recursive=False):

/dls_sw/apps/python/miniforge/4.10.0-0/envs/python3.10/lib/python3.10/site-packages/nexusformat/nexus/tree.py in set_changed(self)
   2276         self._changed = True
   2277         if self.nxgroup:
-> 2278             self.nxgroup.set_changed()
   2279 
   2280     def set_unchanged(self, recursive=False):

/dls_sw/apps/python/miniforge/4.10.0-0/envs/python3.10/lib/python3.10/site-packages/nexusformat/nexus/tree.py in set_changed(self)
   2276         self._changed = True
   2277         if self.nxgroup:
-> 2278             self.nxgroup.set_changed()
   2279 
   2280     def set_unchanged(self, recursive=False):

/dls_sw/apps/python/miniforge/4.10.0-0/envs/python3.10/lib/python3.10/site-packages/nexpy/gui/treeview.py in set_changed(self)
     59             for row in range(self._item.rowCount()):
     60                 for item in self._item.child(row).walk():
---> 61                     self.sync_children(item)
     62             self._view.dataChanged(self._item.index(), self._item.index())
     63             self._view.update()

/dls_sw/apps/python/miniforge/4.10.0-0/envs/python3.10/lib/python3.10/site-packages/nexpy/gui/treeview.py in sync_children(self, item)
     72             names = [child.name for child in children]
     73             if item.node.entries_loaded:
---> 74                 for name in item.node:
     75                     if name not in names:
     76                         item.appendRow(NXTreeItem(item.node[name]))

/dls_sw/apps/python/miniforge/4.10.0-0/envs/python3.10/lib/python3.10/site-packages/nexusformat/nexus/tree.py in __iter__(self)
   4589     def __iter__(self):
   4590         """Implement key iteration."""
-> 4591         return self.entries.__iter__()
   4592 
   4593     def __len__(self):

... last 8 frames repeated, from the frame below ...

/dls_sw/apps/python/miniforge/4.10.0-0/envs/python3.10/lib/python3.10/site-packages/nexusformat/nexus/tree.py in entries(self)
   5450         if _entries != self._entries:
   5451             self._entries = _entries
-> 5452             self.set_changed()
   5453         return _entries
   5454 

RecursionError: maximum recursion depth exceeded while calling a Python object

**Comment by rayosborn** [comment] 2022-06-24 16:51
Thanks for reporting this. I can open the NeXus file and view the contents in a IPython shell, but the bug occurs when NeXpy is checking for any changes requiring updates to the tree. I'll look into it as soon as I can.

**Comment by rayosborn** [comment] 2022-06-27 18:38
This is caused by the need to dynamically update links in the tree in case the parent has changed. I think the updates were being recursively triggered with nested linked groups. The fix requires an update to the [nexusformat](https://github.com/nexpy/nexusformat/) package to add a direct check of whether the link target has changed. Coincidentally, I was intending to release an update to the package this week, so I hope the issue will be fixed then. However, I think you will find that opening nested links groups, at least for the first time, will be slow.

**Comment by rayosborn** [comment] 2022-06-28 15:25
I have released a new version of `nexusformat`, v0.7.6. This should be available on [PyPI](https://pypi.org/project/nexusformat/) now and on conda-forge by tomorrow. In my tests, this fixes the issue, although expanding the `classic_scan` group is still very slow, at least for the first time. Having a large number of embedded link objects is the worst-case scenario for syncing the file tree. In the future, I may be able to speed these things up, but I hope this at least prevents the exceptions you showed. If they don't fix it, please report it here.

**Comment by spc93** [comment] 2022-07-07 17:13
Thanks Ray - sorry about the delay. Yes it works now (from NeXPy). As you said, it is a bit slow, but it works with no errors.

**Closed** 2022-07-20 20:06 UTC
