### ISSUE TITLE
NeXpy won't open after closing if any files listed in settings.ini

### ISSUE THREAD

**Issue by krogstad** [nexpy/nexpy#107] opened 2016-09-28 18:42 UTC
Installed on Windows 7 within a Python 2.7 Anaconda environment.

After closing NeXpy and having some file paths saved in the .nexpy/settings.ini file for future 'open recent' use, NeXpy will not launch, reporting error:

backports.configparser.DuplicateOptionError: While reading from u'C:\Users\xxxxxxx.nexpy\settings.ini' [line  3]: option u'C' in section u'recent' already exists

Deleting all lines beneath [recent] in the settings.ini file will allow NeXpy to launch again.

**Comment by rayosborn** [comment] 2016-09-28 18:53
Can you please post an example of the `settings.ini` file that causes the error?

**Comment by krogstad** [comment] 2016-09-28 19:03
[recent]
C:/Users/b229577/Desktop/CORELLI_relaxor/PMN_006K_norm.nxs
C:/Users/b229577/Desktop/CHESS_relaxor/pzt_a2_100K_combined_needs_redo.nxs
C:/Users/b229577/Desktop/CHESS_relaxor/pmn30pt_100K_rot_combined.nxs

[backups]

**Comment by rayosborn** [comment] 2016-09-28 19:09
It appears that, on Windows, when ConfigParser reads the settings file, it interprets the `C` at the beginning of each line as the key in the key/value pair,  presumably treating the colon as a delimiter, and complains that it is not unique. On Linux or Mac systems, there is no colon in the file path, so the whole string is treated as the key (there is no value in this implementation). I will have to find out how to escape the colon to prevent this interpretation on Windows.

**Comment by jpcastell** [comment] 2017-01-18 22:13
I got the same error after building the lasted pull from git.


--------------------------------------------------------------------------------
Traceback (most recent call last):
  File ".\nexpygui.py", line 30, in <module>
    main()
  File ".\nexpygui.py", line 26, in main
    main(args.filename)
  File "C:\Users\John-Paul\Anaconda3\lib\site-packages\nexpy-0.9.2-py3.5.egg\nexpy\gui\consoleapp.py", line 351, in main
  File "<decorator-gen-116>", line 2, in initialize
  File "C:\Users\John-Paul\Anaconda3\lib\site-packages\traitlets\config\application.py", line 74, in catch_config_error
    return method(app, *args, **kwargs)
  File "C:\Users\John-Paul\Anaconda3\lib\site-packages\nexpy-0.9.2-py3.5.egg\nexpy\gui\consoleapp.py", line 327, in initialize
  File "C:\Users\John-Paul\Anaconda3\lib\site-packages\nexpy-0.9.2-py3.5.egg\nexpy\gui\consoleapp.py", line 188, in init_settings
  File "C:\Users\John-Paul\Anaconda3\lib\site-packages\nexpy-0.9.2-py3.5.egg\nexpy\gui\utils.py", line 124, in __init__
  File "C:\Users\John-Paul\Anaconda3\lib\configparser.py", line 696, in read
    self._read(fp, filename)
  File "C:\Users\John-Paul\Anaconda3\lib\configparser.py", line 1089, in _read
    fpname, lineno)
configparser.DuplicateOptionError: While reading from 'C:\\Users\\John-Paul\\.nexpy\\settings.ini' [line  3]: option 'C' in section 'recent' already exists
--------------------------------------------------------------------------

I delete the entries there and nexpy loads.  I will do some testing to see if I can force the error again.

**Comment by jpcastell** [comment] 2017-01-18 22:16
After deleting the files in the list the program runs however the "open recent" fails to function properly.
This is using Anaconda on windows.  Using linux I do not get this error.  It is likely due to how python in windows handles directory structure slightly differently than mac/linux.

**Comment by jpcastell** [comment] 2017-01-18 22:21
Windows directory structure
------
pwd
Out[2]: 'C:\\Users\\John-Paul\\Documents\\GitHub\\nexpy\\src\\nexpy'
-------

settings.ini file  
[recent]
C = /Users/John-Paul/Desktop/tbni2ge2test.nxs

[backups]


==============

for python in windows to see the directories correctly they whould have to be 
C:\\Users\\John-Paul\\Desktop\\tbni2ge2test.nxs

**Comment by prjemian** [comment] 2017-01-18 22:36
looks like the relevant code is in `nexpy.gui.mainwindow.MainWindow.open_file()` at this line:

    self.update_recent_files(fname)

which could change to

    self.update_recent_files(os.path.abspath(fname))

**Comment by rayosborn** [comment] 2017-01-19 16:07
Sorry I dropped the ball on this one. I should have fixed it before the latest releases. As I said above, the problem is that ConfigParser interprets the `C` before the colon as a key in a key/value pair, instead of part of the key string (there is no value). This happens when the settings file is first read by ConfigParser, which uses a regular expression pattern that interprets the colon as the key/value delimiter. I might be able to fix this by using a different regular expression in NXConfigParser, but it's a little more intrusive than I would have liked. The alternative is to substitute the colon when writing the file path.

**Comment by prjemian** [comment] 2017-01-19 16:16
You are using Qt already.  Consider switching to use QSettings instead of
ConfigParser.  It supports the .ini format.

**Comment by rayosborn** [comment] 2017-01-19 16:24
I did use QSettings before. There was some limitation that made me change to ConfigParser, but I'll have to look through the change logs to remind myself why.

**Comment by rayosborn** [comment] 2017-01-19 22:41
@jpcastell, I've created a pull request, #112, which has a potential fix for this. If you are able to test that this works on Windows, that would be very helpful. At the moment, the backslashes are escaped as double-backslashes in the file path, but I can't see whether that would prevent the open file dialog from working or not.

**Comment by rayosborn** [comment] 2017-01-22 21:33
The double-backslashes shouldn't be a problem. It's a standard way of escaping `\` in the internal string representation, but they are not included when the string is printed.

**Comment by rayosborn** [comment] 2017-01-24 21:03
I have now merged #112, so the current master branch contains the fix for this issue. If someone could test it on a Windows system, I will release a new version as soon as they have confirmed it works.

**Comment by rayosborn** [comment] 2017-01-31 20:13
This should have been fixed in v0.9.3. If it still causes problems, please reopen this issue.

**Closed by rayosborn** 2017-01-31 20:13 UTC
