### ISSUE TITLE
projection bug

### ISSUE THREAD

**Issue by jpcastell** [nexpy/nexpy#95] opened 2016-07-21 13:59 UTC
When taking a cut from a 2d data set using the projection menu there is a small axis bug.
In a xy,Counts type plot if you take a slice along x for a particular y you can run into an error.

say you take y[1] and the entire x range.  This works fine.  If you take x[5] to the end; also fine.  
you get an axis size error when you shorten x from the x[max].  This will still plot however you will not be able to fit the data as len(Counts) no longer equals len(x).

x will have one extra element causing the fit function to fail.

**Comment by rayosborn** [comment] 2016-07-21 22:09
Did your 2D dataset contain bin boundaries rather than centers? I reproduced the problem when the length of the x-axis was (number of x-pixels+1) but not when they were equal.

**Comment by jpcastell** [comment] 2016-07-22 06:16
I used the bins I defined for the histogram2d function.

**Comment by rayosborn** [comment] 2016-07-29 15:50
NeXus, and therefore NeXpy, allows axes to be stored as bin boundaries rather than bin centers, i.e., with one more value than the signal array. I believe I have fixed the fit function failure by ensuring that the axes are converted to bin centers when the FitDialog is initiated. What to return from the Projection Menu is more subtle, and I'm still working on that. I think it is appropriate to maintain bin boundaries where possible, because the translation from centers back to boundaries is not necessarily unique. However, the existing Projection Menu wasn't consistent in what it returned, so I am trying to fix that now. Hopefully, there will be a new release soon with both fixes.

**Comment by rayosborn** [comment] 2016-08-24 16:26
I believe this is fixed in the master branch. Reopen if necessary.

**Closed by rayosborn** 2016-08-24 16:26 UTC
