### ISSUE TITLE
Add plot to tree bug

### ISSUE THREAD

**Issue by jpcastell** [nexpy/nexpy#85] opened 2016-02-23 10:30 UTC
When adding a 2d map (I haven't checked yet for 1d,3d or greater) plot to tree the errors field isn't passed onto the new tree object.

**Comment by jpcastell** [comment] 2016-02-23 11:18
I just checked 1d add plot to tree and the errors are passed along.

**Comment by rayosborn** [comment] 2016-02-23 14:55
I'll try to add that. I guess we left it out because we don't have a way of plotting 2D errors, but it should still be passed along. There are a couple of other fixes in the pipeline that I'll add.

**Comment by rayosborn** [comment] 2016-02-24 02:23
In 2D projections, the errors are transferred. Do you have a specific example?

**Comment by rayosborn** [comment] 2016-08-24 16:33
Closed due inability to reproduce the problem. If you wish to reopen it, please provide example data.

**Closed by rayosborn** 2016-08-24 16:33 UTC
Labels: bug
