### ISSUE TITLE
nexpy from master does not launch on debian 9

### ISSUE THREAD

**Issue by jkotan** [nexpy/nexpy#172] opened 2018-10-04 21:20 UTC
When I try to start nexpy from the master branch on debian 9 I get the following error:

    jkotan@jessie:~/sources$ nexpy
    INFO:root:NeXpy launched
    INFO:root:Log level is INFO
    INFO:root:Python 2.7.13: /usr/bin/python
    INFO:root:IPython v5.1.0
    INFO:root:Matplotlib v2.0.0
    INFO:root:NeXpy v0.10.10+95.g8c5513b.dirty
    INFO:root:nexusformat v0.4.17+34.gdc4a4d8

    (python:14776): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:1214:18: Not using units is deprecated. Assuming 'px'.
    ERROR:root:Exception in GUI event loop
    ---------------------------------------------------------------------------
    TypeError                                 Traceback (most recent call last)
    /home/jkotan/testinst/bin/nexpy in <module>()
	  9     sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
	 10     sys.exit(
    ---> 11         load_entry_point('NeXpy==0.10.10+95.g8c5513b.dirty', 'gui_scripts', 'nexpy')()
	 12     )

    /home/jkotan/testinst/lib/python2.7/site-packages/NeXpy-0.10.10+95.g8c5513b.dirty-py2.7.egg/nexpy/nexpygui.pyc in main()
	 23     args = parser.parse_args()
	 24     from nexpy.gui.consoleapp import main
    ---> 25     main(args.filename)
	 26 
	 27 

    /home/jkotan/testinst/lib/python2.7/site-packages/NeXpy-0.10.10+95.g8c5513b.dirty-py2.7.egg/nexpy/gui/consoleapp.pyc in main(filename)
	365 def main(filename=None):
	366     app = NXConsoleApp()
    --> 367     app.initialize(filename=filename)
	368     app.start()
	369     sys.exit(0)

    <decorator-gen-113> in initialize(self, filename, argv)

    /usr/lib/python2.7/dist-packages/traitlets/config/application.pyc in catch_config_error(method, app, *args, **kwargs)
	 85     """
	 86     try:
    ---> 87         return method(app, *args, **kwargs)
	 88     except (TraitError, ArgumentError) as e:
	 89         app.print_help()

    /home/jkotan/testinst/lib/python2.7/site-packages/NeXpy-0.10.10+95.g8c5513b.dirty-py2.7.egg/nexpy/gui/consoleapp.pyc in initialize(self, filename, argv)
	344         self.init_log()
	345         self.init_tree()
    --> 346         self.init_gui()
	347         self.init_shell(filename)
	348         self.init_colors()

    /home/jkotan/testinst/lib/python2.7/site-packages/NeXpy-0.10.10+95.g8c5513b.dirty-py2.7.egg/nexpy/gui/consoleapp.pyc in init_gui(self)
	269         except Exception:
	270             self.icon_pixmap = None
    --> 271         self.window = MainWindow(self, self.tree, self.settings, self.config)
	272         self.window.log = self.log
	273         global _mainwindow

    /home/jkotan/testinst/lib/python2.7/site-packages/NeXpy-0.10.10+95.g8c5513b.dirty-py2.7.egg/nexpy/gui/mainwindow.pyc in __init__(self, app, tree, settings, config)
	102         rightpane = QtWidgets.QWidget()
	103 
    --> 104         main_plotview = NXPlotView(label="Main", parent=self)
	105         self.panels = NXProjectionPanels(self)
	106         self.panels.setVisible(False)

    /home/jkotan/testinst/lib/python2.7/site-packages/NeXpy-0.10.10+95.g8c5513b.dirty-py2.7.egg/nexpy/gui/plotview.pyc in __init__(self, label, parent)
	275             plotviews[label].close()
	276 
    --> 277         self.figuremanager = new_figure_manager(label)
	278         self.number = self.figuremanager.num
	279         self.canvas = self.figuremanager.canvas

    /home/jkotan/testinst/lib/python2.7/site-packages/NeXpy-0.10.10+95.g8c5513b.dirty-py2.7.egg/nexpy/gui/plotview.pyc in new_figure_manager(label, *args, **kwargs)
	129             num = 1
	130     thisFig = Figure(*args, **kwargs)
    --> 131     canvas = NXCanvas(thisFig)
	132     manager = NXFigureManager(canvas, num)
	133     return manager

    /home/jkotan/testinst/lib/python2.7/site-packages/NeXpy-0.10.10+95.g8c5513b.dirty-py2.7.egg/nexpy/gui/plotview.pyc in __init__(self, figure)
	162     def __init__(self, figure):
	163 
    --> 164         FigureCanvas.__init__(self, figure)
	165 
	166         self.setSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding,

    /usr/lib/python2.7/dist-packages/matplotlib/backends/backend_qt4agg.pyc in __init__(self, figure)
	 74         if DEBUG:
	 75             print('FigureCanvasQtAgg: ', figure)
    ---> 76         FigureCanvasQT.__init__(self, figure)
	 77         FigureCanvasQTAggBase.__init__(self, figure)
	 78         FigureCanvasAgg.__init__(self, figure)

    /usr/lib/python2.7/dist-packages/matplotlib/backends/backend_qt4.pyc in __init__(self, figure)
	 64 
	 65         # Note different super-calling style to backend_qt5
    ---> 66         QtWidgets.QWidget.__init__(self)
	 67         FigureCanvasBase.__init__(self, figure)
	 68         self.figure = figure

    TypeError: __init__() takes exactly 2 arguments (1 given)

On debian 9 matplotlib is in 2.0.0

**Comment by rayosborn** [comment] 2018-10-04 21:43
@tacaswell, this is the same error that was fixed in an old Matplotlib PR, https://github.com/matplotlib/matplotlib/pull/5195. Is there a connection? The error is for a Python 2 Matplotlib v2.0.0 installation.

**Comment by jkotan** [comment] 2018-10-04 21:57
It looks like it is related. However in the PR it is mentioned Matplotlib 1.5.0

The folloging change:


    diff --git a/src/nexpy/gui/pyqt.py b/src/nexpy/gui/pyqt.py
    index 681eace..ec3aeca 100644
    --- a/src/nexpy/gui/pyqt.py
    +++ b/src/nexpy/gui/pyqt.py
    @@ -9,7 +9,7 @@ try:
     except ImportError:
	 pass

    -from qtpy import QtCore, QtGui, QtWidgets
    +from matplotlib.backends.qt_compat import QtCore, QtGui, QtWidgets
     if QtCore.__name__.lower().startswith('pyqt5'):
	 os.environ['QT_API'] = 'pyqt5'
	 QtVersion = 'Qt5Agg'


fixes the issue.

**Comment by rayosborn** [comment] 2018-10-05 01:34
This seems to be a Python 2 issue. I've confirmed that the same issue occurs in Mac OS with Python 2.7. The `qtpy` package claims Python 2.7 compatibility, so I'm not sure what the issue is. I will revert to the `qt_compat` module if we don't find a solution soon.

**Comment by jkotan** [comment] 2018-10-05 07:03
I think `qtpy` cannot have compatible API with PyQt5/PyQt4/PySide for py2 and py3 at one time. So if you choose to use `qtpy` you get some limitation for `matplotlib` which uses `PyQt` directly.

**Comment by rayosborn** [comment] 2018-10-05 14:15
Since Matplotlib has not moved over to the qtpy package yet, I am willing to go back to using their `qt_compat` module. We may have to offer `qtpy` in the future if it becomes a _de facto_ standard, but it will probably have to be within an exception clause to maintain backward compatibility.

**Comment by rayosborn** [comment] 2018-10-11 15:56
Should be fixed by #173.

**Comment by tacaswell** [comment] 2018-10-22 19:19
> I think `qtpy` cannot have compatible API with PyQt5/PyQt4/PySide for py2 and py3 at one time.

Why do you say this?

I can not reproduce this issue with

```
15:17 $ pip list                                                                                                              
Package                            Version              Location                                                              
---------------------------------- -------------------- --------------------------------                                      
ansi2html                          1.5.2                                                                                      
arandr                             0.1.9                                                                                      
backports-abc                      0.5                                                                                        
backports.functools-lru-cache      1.5                                                                                        
backports.shutil-get-terminal-size 1.0.0                                                                                      
beautifulsoup4                     4.6.0                                                                                      
bleach                             3.0.2                                                                                      
chardet                            3.0.4                                                                                      
Cheetah                            2.4.4                                                                                      
configparser                       3.5.0                                                                                      
cycler                             0.10.0                                                                                     
decorator                          4.3.0                                                                                      
defusedxml                         0.5.0                                                                                      
entrypoints                        0.2.3                                                                                      
enum34                             1.1.6                                                                                      
functools32                        3.2.3.post2                                                                                
futures                            3.2.0                                                                                      
Genshi                             0.7                                                                                        
gyp                                0.1                                                                                        
h5py                               2.8.0                                                                                      
html5lib                           0.999999999                                                                                
ipaddress                          1.0.22                                                                                     
ipykernel                          4.10.0                                                                                     
ipython                            5.8.0                                                                                      
ipython-genutils                   0.2.0                                                                                      
ipywidgets                         7.4.2                                                                                      
Jinja2                             2.10                                                                                       
jsonschema                         2.6.0                                                                                      
jupyter                            1.0.0                                                                                      
jupyter-client                     5.2.3                                                                                      
jupyter-console                    5.2.0                                                                                      
jupyter-core                       4.4.0                
kiwisolver                         1.0.1                
lxml                               4.2.1                
MarkupSafe                         1.0                  
matplotlib                         2.2.3                
mercurial                          4.5.3                
mistune                            0.8.4                
nbconvert                          5.4.0                
nbformat                           4.4.0                
NeXpy                              0.10.10+110.g072d0b1 /home/tcaswell/src/bnl/nexpy/src
nexusformat                        0.4.17               
notebook                           5.7.0                
numpy                              1.13.3               
olefile                            0.45.1               
pandocfilters                      1.4.2                
pathlib2                           2.3.2                
pexpect                            4.2.1                
pickleshare                        0.7.5                
pip                                18.1                 
pkg-resources                      0.0.0                
prometheus-client                  0.4.2                
prompt-toolkit                     1.0.15               
ptyprocess                         0.6.0                
pycairo                            1.16.2               
pycurl                             7.43.0.1             
pydbus                             0.6.0                
Pygments                           2.2.0                
pygobject                          3.26.1               
pyparsing                          2.2.2                
python-dateutil                    2.7.3                
pytz                               2018.5               
PyYAML                             3.12                 
pyzmq                              17.1.2               
qtconsole                          4.4.2                
QtPy                               1.5.2                
scandir                            1.9.0                
scipy                              1.1.0                
scour                              0.36                 
Send2Trash                         1.5.0                
setuptools                         40.4.3               
simplegeneric                      0.8.1                
singledispatch                     3.4.0.3              
six                                1.11.0               
spectacle                          0.25                 
subprocess32                       3.5.3                
terminado                          0.8.1                
testpath                           0.4.2                
tornado                            5.1.1                
traitlets                          4.3.2                
unity-lens-photos                  1.0                  
urlgrabber                         3.10.2               
virtualenv                         15.1.0               
wcwidth                            0.1.7                
webencodings                       0.5                  
wheel                              0.32.2               
widgetsnbextension                 3.4.2  
```

I strongly suspect that this is a local installation or configuration issue.

**Comment by tacaswell** [comment] 2018-10-22 19:21
Nor with 

```
15:21 $ pip list                                                                                                              
Package                            Version              Location                                                              
---------------------------------- -------------------- --------------------------------                                      
ansi2html                          1.5.2                                                                                      
arandr                             0.1.9                                                                                      
backports-abc                      0.5                                                                                        
backports.functools-lru-cache      1.5                                                                                        
backports.shutil-get-terminal-size 1.0.0                                                                                      
beautifulsoup4                     4.6.0                                                                                      
bleach                             3.0.2                                                                                      
chardet                            3.0.4                                                                                      
Cheetah                            2.4.4                                                                                      
configparser                       3.5.0                                                                                      
cycler                             0.10.0                                                                                     
decorator                          4.3.0                                                                                      
defusedxml                         0.5.0                                                                                      
entrypoints                        0.2.3                                                                                      
enum34                             1.1.6                                                                                      
functools32                        3.2.3.post2                                                                                
futures                            3.2.0                                                                                      
Genshi                             0.7                                                                                        
gyp                                0.1                                                                                        
h5py                               2.8.0                                                                                      
html5lib                           0.999999999                                                                                
ipaddress                          1.0.22                                                                                     
ipykernel                          4.10.0                                                                                     
ipython                            5.8.0                                                                                      
ipython-genutils                   0.2.0                                                                                      
ipywidgets                         7.4.2                                                                                      
Jinja2                             2.10                                                                                       
jsonschema                         2.6.0                                                                                      
jupyter                            1.0.0                                                                                      
jupyter-client                     5.2.3                                                                                      
jupyter-console                    5.2.0                                                                                      
jupyter-core                       4.4.0                
kiwisolver                         1.0.1                
lxml                               4.2.1                
MarkupSafe                         1.0                  
matplotlib                         2.0.2                
mercurial                          4.5.3                
mistune                            0.8.4                
nbconvert                          5.4.0                
nbformat                           4.4.0                
NeXpy                              0.10.10+110.g072d0b1 /home/tcaswell/src/bnl/nexpy/src
nexusformat                        0.4.17               
notebook                           5.7.0                
numpy                              1.13.3               
olefile                            0.45.1               
pandocfilters                      1.4.2                
pathlib2                           2.3.2                
pexpect                            4.2.1                
pickleshare                        0.7.5                
pip                                18.1                 
pkg-resources                      0.0.0                
prometheus-client                  0.4.2                
prompt-toolkit                     1.0.15               
ptyprocess                         0.6.0                
pycairo                            1.16.2               
pycurl                             7.43.0.1             
pydbus                             0.6.0                
Pygments                           2.2.0                
pygobject                          3.26.1               
pyparsing                          2.2.2                
python-dateutil                    2.7.3                
pytz                               2018.5               
PyYAML                             3.12                 
pyzmq                              17.1.2               
qtconsole                          4.4.2                
QtPy                               1.5.2                
scandir                            1.9.0                
scipy                              1.1.0                
scour                              0.36                 
Send2Trash                         1.5.0                
setuptools                         40.4.3               
simplegeneric                      0.8.1                
singledispatch                     3.4.0.3              
six                                1.11.0               
spectacle                          0.25                 
subprocess32                       3.5.3                
terminado                          0.8.1                
testpath                           0.4.2                
tornado                            5.1.1                
traitlets                          4.3.2                
unity-lens-photos                  1.0                  
urlgrabber                         3.10.2               
virtualenv                         15.1.0               
wcwidth                            0.1.7                
webencodings                       0.5                  
wheel                              0.32.2               
widgetsnbextension                 3.4.2 
```

**Comment by jkotan** [comment] 2018-10-22 20:49
@tacaswell, have you tried to use debian 9 VM or debian Dockers to reproduce the problem?
 On debian stretch  there is qtpy 1.2.1 
You cannot forse  people to use pip installation. So either you support the current stable Linux distribution or not.

**Comment by rayosborn** [comment] 2018-12-04 20:24
I will revisit this before releasing v0.11 (or when Matplotlib requires us to use qty, whichever is sooner).

**Closed by rayosborn** 2018-12-04 20:24 UTC
